// <auto-generated />
using System;
using AFAConsultant.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AFAConsultant.Migrations
{
    [DbContext(typeof(AppdbContext))]
    partial class AppdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AFAConsultant.Models.Aboutus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(280)
                        .HasColumnType("nvarchar(280)");

                    b.Property<int>("Success_Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Total_Team_Members")
                        .HasColumnType("int");

                    b.Property<int>("Total_Visa_Categories")
                        .HasColumnType("int");

                    b.Property<int>("Total_Visa_Processes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_aboutus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is description",
                            Success_Rate = 100,
                            Title = "ABOUT1",
                            Total_Team_Members = 21,
                            Total_Visa_Categories = 31,
                            Total_Visa_Processes = 2000
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Contactus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacebookLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TiktokLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TwitterLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_contactus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "Kotli",
                            Address2 = "kotli",
                            Email1 = "naseer@gmail.com",
                            Email2 = "insram@gmail.com",
                            FacebookLink = "facebook.com",
                            InstagramLink = "instagram.com",
                            PhoneNumber1 = "12345",
                            PhoneNumber2 = "12345",
                            TiktokLink = "tiktok.com",
                            TwitterLink = "twitter.com"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Countries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Country_PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag_PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country_PicUrl = "image.jpg",
                            Flag_PicUrl = "image.jpg",
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Professionals", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_professionals");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is Muhammad Naseer",
                            Email = "naseer@gmail.com",
                            Name = "Naseer",
                            PhoneNumber = "12345",
                            PicUrl = "image.jpg"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.QueryMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_querymessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "naseershabbir@gmail.com",
                            Message = "This is my Message",
                            Name = "Naseer",
                            PhoneNumber = "12345",
                            Subject = "Problem"
                        },
                        new
                        {
                            Id = 2,
                            Email = "naseershabbir@gmail.com",
                            Message = "This is my Message",
                            Name = "Naseer",
                            PhoneNumber = "12345",
                            Subject = "Problem"
                        },
                        new
                        {
                            Id = 3,
                            Email = "naseershabbir@gmail.com",
                            Message = "This is my Message",
                            Name = "Naseer",
                            PhoneNumber = "12345",
                            Subject = "Problem"
                        },
                        new
                        {
                            Id = 4,
                            Email = "naseershabbir@gmail.com",
                            Message = "This is my Message",
                            Name = "Naseer",
                            PhoneNumber = "12345",
                            Subject = "Problem"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_review");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        },
                        new
                        {
                            Id = 2,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        },
                        new
                        {
                            Id = 3,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        },
                        new
                        {
                            Id = 4,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        },
                        new
                        {
                            Id = 5,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        },
                        new
                        {
                            Id = 6,
                            Designation = "programmer",
                            Message = "Good",
                            Name = "Muhammad Naseer",
                            PicUrl = "image.jpg",
                            Rating = 4
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("LogoFavicon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LogoFavicon = "image.jpg",
                            Name = "AFAConsultant"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PicURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_slider");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is Slider",
                            PicURL = "image.jpg",
                            Title = "Slider"
                        });
                });

            modelBuilder.Entity("AFAConsultant.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("tbl_user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Muhammad Naseer",
                            ImageName = "naseer.jpg",
                            Password = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Muhammad Naseer",
                            ImageName = "naseer.jpg",
                            Password = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("JobApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecializationArea")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAddress2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("jobApplications");
                });
#pragma warning restore 612, 618
        }
    }
}
